[package]
name = "seven"
version = "0.1.0"
authors = ["Patrik Lundgren <patrik.lundgren@westermo.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
