[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
anyhow = "1.0.51"
either = "1.6.1"
simple-error = "0.2.3"


[lib]
name = "aoc"
path = "src/lib.rs"
